name: CowCannon
version: 1.0
main: org.cowCannon.cowCannon.CowCannon
api-version: 1.19
softdepened: [ ProtocolLib, PlaceholderAPI, Vault ]
commands:
  cow:
    description: "This command spawns a cow who can explode!"
    usage: "/cow [set/baby] [entityType]"
    aliases: [cownnanon]
    permission: cowcannon.command.cow
    permission-message: "&cYou do not have permission to spawn an exploding cow!"
  butterfly:
    description: "Toggle particle effect"
    usage: "/butterfly"
    permission: cowcannon.command.butterfly
    permission-message: "&cYou do not have permission to enable butterfly"
  customItem:
    description: "Create custom items effects"
    usage: "/customitem [itemType]"
    aliases: [cm]
    permission: cowcannon.command.customitem
    permission-message: "&cYou do not have permission to do that"
  gui:
    description: "Opens a gui"
    usage: "/gui"
    aliases: [guis]
    permission: cowcannnon.command.gui
    permission-message: "&CSorry, you cant open that!"

permissions:
  cowcannon.command.cow:
    default: op
  cowcannon.command.gui:
    default: op
  cowcannon.cow.use:
    default: op
